// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJhq0D7_IUuUzoqFsU5HZnzrLQPRn4_Kc',
    appId: '1:784981661937:web:d957dde5469294f273b150',
    messagingSenderId: '784981661937',
    projectId: 'streamx-f8f2d',
    authDomain: 'streamx-f8f2d.firebaseapp.com',
    storageBucket: 'streamx-f8f2d.appspot.com',
    measurementId: 'G-56M02MRDPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcEQ64VfV8DOvRvZ0_y_9XRSraLipXpJM',
    appId: '1:784981661937:android:83deb91ed61d8c5773b150',
    messagingSenderId: '784981661937',
    projectId: 'streamx-f8f2d',
    storageBucket: 'streamx-f8f2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVCXRMRetYxwDRLImiOmTDX09Duf99rMY',
    appId: '1:784981661937:ios:506c7a5859dcae3673b150',
    messagingSenderId: '784981661937',
    projectId: 'streamx-f8f2d',
    storageBucket: 'streamx-f8f2d.appspot.com',
    iosBundleId: 'com.example.streamx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVCXRMRetYxwDRLImiOmTDX09Duf99rMY',
    appId: '1:784981661937:ios:40f15388e2adca9e73b150',
    messagingSenderId: '784981661937',
    projectId: 'streamx-f8f2d',
    storageBucket: 'streamx-f8f2d.appspot.com',
    iosBundleId: 'com.example.streamx.RunnerTests',
  );
}
